Feature/helm chart
NBISweden/rems-operation pull request #12
Opened 2020-08-20 07:53 UTC by airenzp

This branch adds the rems-chart folder that contains  the rems kubernetes deployment using chart. It resolves  #8 issue

2020-08-20 09:40 UTC, MalinAhlberg approved these changes
Looks good to me!
Added two commits: fixed some of my old typos / bad formulations in the Readme.

2020-08-24 15:14 UTC, viklund requested changes
Really nice!

But... When running this chart I get these pods in my kubernetes cluster:

```
$ kubectl get pods
NAME                           READY   STATUS    RESTARTS   AGE
svclb-database-xxm8t           1/1     Running   0          60s
svclb-database-8hctb           1/1     Running   0          60s
svclb-database-g76bq           1/1     Running   0          60s
svclb-database-wfp49           1/1     Running   0          60s
rems-chart-84b84b4cb6-8jcgr    1/1     Running   0          60s
database-fd4c7965-mt5tw        1/1     Running   0          60s
elixir-rems-67dc84b87f-m74k4   1/1     Running   0          60s
rems-5556c9669f-852nt          1/1     Running   0          60s
```

`rems`, `elixir-rems` and the `database` are described in the readme. But what is `svclb-database` and `rems-chart`?

Also I don't think we need the autoscaler for this. It's enough with just one pod each for `rems` and the `rems-elixir-proxy`, the database is fine with just one for now as well.

2020-08-25 20:31 UTC, airenzp commented on rems-chart/values.yaml
> +rems:
I have now removed all the extra files provided in the default deployment, that I used as an example for ours. They were causing the rems-chart container to be deployed. The other containers named svclb-* never appeared for me. I hope they are gone now anyway. 
I also removed the properties included in the values file that I noticed were not used by us.

2020-08-26 11:18 UTC, airenzp commented on rems-chart/values.yaml
> +rems:
I have now removed most of the properties you mentioned, except the serviceAccount because otherwise the install fails, and the nodePort type for the rems, that I needed to be able to export the port in my localhost.

2020-08-26 13:11 UTC, viklund approved these changes

2020-08-26 13:11 UTC, merged